baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'DGG Political Action'

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"

[params]
  favicon = "favicon.ico"

[module]
[[module.imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'